### ISSUE TITLE
Product 컴포넌트 수정 필요

### ISSUE THREAD

**Issue by Dayhun** [SoEasyTeam/Dev.Town#32]
1. width값 추가
const ProductItemBox = styled.div`width: 140px;`

2. txt-productName에 스타일 코드 추가

.txt-productName {
        text-overflow: ellipsis;
        white-space: nowrap;
        overflow: hidden;
}

요청합니다~

**Comment by chuhoon** [comment]
수정하였습니다 확인부탁드리겠습니다👍

**Comment by Dayhun** [comment]
확인했습니다 수고하셨습니다~!
